seg_controller:
  ros__parameters:
    controller_type: SegMin # SegZeros, SegMin or SegMinD
    
    cmd_vel_topic: /cmd_vel
    rgb_topic: /camera/image_raw
    
    # model_file: /home/fastroof/dev_ws/src/SegMinNavigation/row_crop_follow/models/lr_aspp/vineyard_tot_pergolato/vineyards_segmentation_binary.tflite
    model_file: src/SegMinNavigation/row_crop_follow/models/lr_aspp/trees_covivio/trees_segmentation_binary.tflite
    inference_device: gpu # cpu or gpu
    input_width_network: 224
    input_height_network: 224
    normalization: imagenet

    lin_vel_gain: 1.0
    ang_vel_gain: 3.0
    max_lin_vel: 0.1
    max_ang_vel: 1.0
    ema_filter_alpha: 0.5
    depth_threshold: 5.0
    confidence_threshold: 0.7
    
    show_result: True